[2020-08-02 03:49:20,312] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: product_price_pipeline.get_product_upc_and_description 2020-08-02T03:49:08.443486+00:00 [queued]>
[2020-08-02 03:49:20,374] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: product_price_pipeline.get_product_upc_and_description 2020-08-02T03:49:08.443486+00:00 [queued]>
[2020-08-02 03:49:20,374] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-08-02 03:49:20,375] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-08-02 03:49:20,381] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-08-02 03:49:20,412] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): get_product_upc_and_description> on 2020-08-02T03:49:08.443486+00:00
[2020-08-02 03:49:20,416] {standard_task_runner.py:53} INFO - Started process 594 to run task
[2020-08-02 03:49:20,547] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: product_price_pipeline.get_product_upc_and_description 2020-08-02T03:49:08.443486+00:00 [running]> fa6566bbdf60
[2020-08-02 03:49:20,578] {taskinstance.py:1128} ERROR - [Errno 2] File b'dataset/products-lookup-table.csv' does not exist: b'dataset/products-lookup-table.csv'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/product_price_pipeline.py", line 17, in get_product_upc_and_description
    df = pandas.read_csv('dataset/products-lookup-table.csv', header=1)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'dataset/products-lookup-table.csv' does not exist: b'dataset/products-lookup-table.csv'
[2020-08-02 03:49:20,584] {taskinstance.py:1185} INFO - Marking task as FAILED.dag_id=product_price_pipeline, task_id=get_product_upc_and_description, execution_date=20200802T034908, start_date=20200802T034920, end_date=20200802T034920
[2020-08-02 03:49:30,153] {logging_mixin.py:112} INFO - [2020-08-02 03:49:30,152] {local_task_job.py:103} INFO - Task exited with return code 1
